### ISSUE TITLE
If we make use of default ef core QueryBuilder instead of SapphireQueryBuilder then this approach of query building will be more useful

### ISSUE THREAD

**Issue by chandrakantnaik789** [SapphireDb/SapphireDb#20]
I am looking for some thought and ideas like this approach.

**Comment by morrisjdev** [comment]
Hi.
I don't think that's possible. I need to know exactly what the query does.
I was not able to get that information when only using the Query Builder from EF Core.
If you have an idea how to get that information I'm open for it.

What operators are missing for your requirements?

Best regards
Morris

**Comment by chandrakantnaik789** [comment]
Hi, 
Actually, I am finding a solution for a problem

public override int SaveChanges() I had overridden SaveChanges() on dbContext but after using SapphireDbContext I am unable to override the SaveChanges anymore. Is there any solution to this problem?

**Comment by morrisjdev** [comment]
Hi.

How did you override the method?
