### ISSUE TITLE
As of 3.1.6 Websocket connection fails with a 400 error

### ISSUE THREAD

**Issue by adriani10** [SapphireDb/SapphireDb#23]
Tested 3.1.6 to see if field error persisted, it does and also it gives a persistent websocket socket handshake 400 error with a React Client

**Comment by morrisjdev** [comment]
Hi.
Thank you for reporting an issue.
Can you provide example code to reproduce the error?

Best regards
Morris

**Comment by adriani10** [comment]
Hi Morris, yes, this is how I have it on React Client. This code works before 3.1.6. After that it gives me a websocket handshake 400 error


`useEffect(() => {
  
  var AuthToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbCBDYXBpdGFuIiwianRpIjoiMmQ5NTZlOTEtY2Q0Zi00MDNlLTkxMmItMDlhZDA5M2ZmMDdmIiwiaWF0IjoiMDQvMTIvMjAyMSAwNjo1NzowNiIsIklkIjoiMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJFbCBDYXBpdGFuIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoicm9uaV9tZXhAaG90bWFpbC5jb20iLCJBY2Nlc3NMZXZlbCI6IjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNjE4MjEwNjI2LCJleHAiOjE2NTQyMTA2MjYsImlzcyI6InNhcHBoaXJlIn0.CvhA1Ur_UpMggxiHFXTlsFXNSzjyaBcyIMI5zn_xIVY';

  var db = new SapphireDb({
    useSsl: true,
    serverBaseUrl: 'localhost:44328',
    apiKey: 'sapphire',
    apiSecret: 'F6249E39DD6FBF6AA29D1D943390288392E6A819DC17FA057934EC3D48EAC06A06DE51B6DF6DBCD0BA8049C13B151EC71DEE0AD20C9E74237B8990D997E35968',
    connectionType: 'websocket',
  }, undefined, undefined, undefined, AuthToken);
  
  //db.setAuthToken(AuthToken);
  
  //@ts-ignore
  let userInfo = db.collection('Users').include('Teams').include('XboxUsers').where(['id', '==', 2]).first().values();
  userInfo.subscribe(function (userinfo) {
    let userAux = userinfo as User;
    setUser(userAux);
  }); }, []);`

**Comment by morrisjdev** [comment]
Did you upgrade the client to the latest alpha version (3.1.4) too, when using an alpha version in backend? The auth token now gets transferred in header for better security, but the old client tries to send it as query parameter.

**Comment by adriani10** [comment]
I updated client and the error is fixed, however it's worth noting that I had to infer that this line was necessary instead of the one listed in the documentation. Thanks:

`                        string authorizationToken = SapphireAuthenticationHelper.GetWebsocketAuthorizationHeader(ctx.Request);
`

**Comment by morrisjdev** [comment]
Oh yes I'm sorry. You're absolutely right. The documentation is already updated but not published because of the alpha version.
