### ISSUE TITLE
long polling connection type dropping on chrome sometimes

### ISSUE THREAD

**Issue by orialmog** [SapphireDb/SapphireDb#25]
Hi Morris, 

Firstly we **really love** this project and am using it in our offerings at work for several clients, however we are trying to get to grips with some issues we experiencing using long polling, we chose long polling due to the unique network restrictions in place at some of the clients

The issue at the moment is calling action handlers **between** active connections on chrome, seems the connection drops on chrome periodically ( when there are concurrent users ) and we get and "no connection" exception thrown from middleware 

Anecdotally does not happen on Firefox, we arent 100% sure of this but some manual testing seems to confirm this, the http connection /poll stays open on Firefox and does not close periodically and therefore we do not have the "no connection" exception thrown there, just happening on chrome when there are a few users online.

We think its due to code in the ShouldRemove function in PollConnection

`var result = !pollInProgress && lastPoll < DateTime.UtcNow.AddSeconds(-5d);`

If we extend this timeout to say a few hours it seems to resolve the "no connection" exception when firing action handlers as its keeping the existing http call to /poll open and using an active connection id.

- Could you shed some light as to why this timeout is so short? and the idea behind the locking mechanism, we cant clearly see why this PollConnection class has this lock and wait logic and what the thinking behind it was. I thought long polling meant no persistent connection and instead periodic requests to collect changes, seems this implementation is actually a "persistent connection" ? 

- If we extend this timeout to a few hours do you think this would be a suitable interim solution, I believe the downside is we would increase the memory pressure by keeping all the connectionids around for so long. I cant forsee other issues so I ask your opinion.

Looking forward to seeing how this project develops

**Comment by morrisjdev** [comment]
Hi @orialmog,

thank you, I'm glad you like the project.

Yes it would definitly be an idea to increase the timeout. I didn't encounter any issue in a production environment using the timeout, thats the reason I didn't invest further into improving the implementation. 

If you're interested:
I put some effort in improving the communication logic and to make it more stable. Therefore I switchted to SignalR, to outsource the Bi-Directional stuff, which is working great. You can find the current stable code in the branch **update**. There is currently no build or released version for it neither an updated documentation, but that could be easily done. I'll do my best, to publish a new pre-release in the next days and keep you updated. 

If you want to try it out know, feel free to copy the code into your code-base. You have to install the npm package @microsoft/signalr in your frontend application. The dependency axios is no longer neccessary.
The server side application should be upgraded to .NET 6. The usage on server side also changed a bit. The DbContext does not need to derive from SapphireDbContext anymore, this now works by using EF Core interceptor, introduced in EF Core 5.

Hope this helps you. If you have any question, feel free to ask, I'll do my best to help you.

Best regards,
Morris

**Comment by orialmog** [comment]
That's awesome news! I know my CTO will love this too,
Ill implement the timeout change for the moment and will take a look at the update branch.
Thank you
