### ISSUE TITLE
Publish base NPM Library for Node/JavaScript

### ISSUE THREAD

**Issue by tracker1** [SapphireDb/SapphireDb#3]
Would suggest abstracting out the core pieces of the angular library, or a JS build of the dart library for general JS use with either Node and/or Browser for non-angular use cases (such as Vue or React).

**Comment by morrisjdev** [comment]
Already planned and I'll work on it soon.

**Comment by tracker1** [comment]
@morrisjdev cool... just a minor suggestion, if you write the library to use fetch api, you could have a separate "browser" entry point for use with browserify/webpack that uses the window.fetch, and the node entry use node-fetch.

**Comment by morrisjdev** [comment]
Hi.
I moved the code base to a seperate js-only project: [https://www.npmjs.com/package/sapphiredb](https://www.npmjs.com/package/sapphiredb)
I decided to use axios and now the client also works with NodeJs.
