### ISSUE TITLE
No Blazor client?

### ISSUE THREAD

**Issue by darrylryan** [SapphireDb/SapphireDb#4]
Now that we have Blazor WebAssembly that lets us run C# on the client side, it would be really cool to have a C# port of the client that is designed to run in the browser with offline support etc.

**Comment by morrisjdev** [comment]
Yes I'm working on it. The current pre pre version is located [here](https://github.com/SapphireDb/SapphireDb-Net) and as I said work in progress. But thank you for the note and the +1 interest in a .Net implementation.

**Comment by darrylryan** [comment]
Oooh I didn't see that, its quite far along already! Looks really promising.
